### PR TITLE
fix(`no-callback-in-promise`): false triggering of callback

### LINKED ISSUE #572: False positive of `no-callback-in-promise` in `7.2.0`
In many different cases. Example:
```js
'use strict';
var call = require('../internals/function-call');

module.exports = function (record, fn, ITERATOR_INSTEAD_OF_RECORD) {
  var iterator = ITERATOR_INSTEAD_OF_RECORD ? record : record.iterator;
  var next = record.next;
  var step, result;
  while (!(step = call(next, iterator)).done) { // 8:24  error  Avoid calling back inside of a promise  promise/no-callback-in-promise
    result = fn(step.value);
    if (result !== undefined) return result;
  }
};
```

### PR DESCRIPTION
**Pull request by brettz9**
**What is the purpose of this pull request?**

- [ ] Documentation update
- [x] Bug fix
- [ ] New rule
- [ ] Changes an existing rule
- [ ] Add autofixing to a rule
- [ ] Other, please explain:

**What changes did you make? (Give an overview)**

Fixes regression with false triggering by callback

Fixes #572

### CODE REVIEW

File: __tests__/no-callback-in-promise.js [hunk 1]
```diff
@@ -46,6 +46,13 @@ ruleTester.run('no-callback-in-promise', rule, {
       code: 'a.then(next).catch(next)',
       options: [{ exceptions: ['next'] }],
     },
+
+    // #572
+    `
+        while (!(step = call(next, iterator)).done) {
+          if (result !== undefined) break;
+        }
+      `,
```
Comment (scagood) [inline __tests__/no-callback-in-promise.js:55]: It may be worth adding both bad examples 🤔

```suggestion
    // #572
    `while (!(step = call(next, iterator)).done) {
       if (result !== undefined) break;
     }`,
    // https://github.com/eslint-community/eslint-plugin-promise/issues/572#issuecomment-2501505747
    `function hasCallbackArg(callback) {
       console.log(callback);
     }`,
```

File: rules/no-callback-in-promise.js [hunk 2]
```diff
@@ -67,20 +68,30 @@ module.exports = {
...
-            CB_BLACKLIST.includes(name) &&
-            (timeoutsErr || !TIMEOUT_WHITELIST.includes(callingName))
-          ) {
-            context.report({
-              node: node.arguments[0],
-              messageId: 'callback',
-            })
+          if (hasPromiseCallback(node)) {
+            const callingName = node.callee.name || node.callee.property?.name
+            const name = node.arguments?.[0]?.name
```
Comment (scagood) [inline rules/no-callback-in-promise.js:73]: It may be worth moving this up a block and not redeclaring it on `:90`

**Review by ota-meshi — APPROVED** [review]
LGTM! Thank you!
